### ISSUE TITLE
TEmarker_bed.py need repeatmasker?

### ISSUE THREAD

**Issue by Morriyaty** [yanhaidong1/TEmarker#2]
Hi:

When I run TEmarker_bed.py, it showd :
    "Cannot find repeatmasker executable, please check if it has been installed."

But it seems repeatmasker didn't use in the manual.pdf. Is this right?

Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

If you want to use the TEFLoN or jitterbug, you need to install the repeatmasker.
I will update the manual. Thanks for reporting this issue.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi,

I want to use mcclintock but I have to provide the path of RepeatMasker. Is this the script bug? 

I also have one question:
   the output bed file in TEmarker_bed.py is obtained from which software in mcclintock ?

Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

I just fixed this issue that you do not need to provide the path of repeatmasker. You can download the new TEmarker_bed.py to run. 

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi: 

Thanks a lot. I will run it later.

Bests,
Yinjia

**Comment by Morriyaty** [comment]
Hi

I meet an unexpected error when I run TEmarker_bed.py 

samtools executable can be found
bwa executable can be found
step
SETUP            checking fasta: /home/ug0134/Example_dir_step0/test_genome.fasta
SETUP            checking fasta: /home/ug0134/Example_dir_step0/TE.lib
SETUP            McClintock Version: ccb36d98caaa35b4203e935827b6051fe4e2a830
Job counts:
	count	jobs
	1	make_consensus_fasta
	1	make_reference_fasta
	1	make_te_annotations
	3
PROCESSING       making consensus fasta
PROCESSING       consensus fasta created
PROCESSING       making reference fasta
PROCESSING       reference fasta created
PROCESSING       making reference TE annotations
PROCESSING       no reference TEs provided... finding reference TEs with RepeatMasker &> /home/ug0134/Example_dir_step0/working_dir_step_0/output_mcclintock/annotation/logs/20220521.135854.4063434/processing.log
PROCESSING       reference TE annotations created
Traceback (most recent call last):
  File "/home/ug0134/Software/TEmarker/TEmarker_bed.py", line 863, in <module>
    main()
  File "/home/ug0134/Software/TEmarker/TEmarker_bed.py", line 448, in main
    genome_fl_nm = mt.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

My command is  
TEmarker_bed.py -d working_dir_step_0 -o output_dir_step_0 --mcclintock /home/ug0134/Software/mcclintock/mcclintock.py -fastq_d fastq_dir -fas_f test_genome.fasta -lib_f TE.lib -pros_n 10

How can I fix it?

Bests,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

Please use the new TEmarker_bed.py and try again. Thanks
The possible issue is in default setting, the TEmarker thinks your input -fas_f is xxx/test_genome.fasta where 'xxx' is one directory. I fixed this issue.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi,

I have lots of samples to run the pipeline, I need to put all the fastq reads into fastq_dir, is that right? Otherwise, what should  I do to run it?

Thanks,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

I recommend to run one sample with many cores to try first and estimate how much time you will spend to run. TEmarker provides multiple choices like including McClintock tools and some other TIP detecting tools. Different tools allow you have different time to run. You can check this literature (figure 9) that mentions the time cost: https://mobilednajournal.biomedcentral.com/articles/10.1186/s13100-019-0197-9. 

You can put all the fastq reads into the fastq_dir, but it may take much time to run if you include some tools requiring so much running time.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi, 

I am sorry to bother you. When I run 
     TEmarker_bed.py  -d work_dir_step_0 -o output_dir_0 --mcclintock ~software/mcclintock/mcclintock.py  -fastq_d fastq_dir -fas_f test_genome.fasta -lib_f TE.lib -tool ngs_te_mapper2,retroseq,temp2,te-locate,popoolationte2  -pros_n 20
It run successfully but I didn't find any output files in output_dir_0.  How can I fix it :) ?

Best,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

It looks like the running process is not finished or something wrong. Would you check whether there are some output from working_dir_step_0? All the output files in the output_dir_0 will be copied from bam and bed files in the working_dir_step_0.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi,

There are some files in working_dir_step_0 but nothing in output_dir_0. And the log.txt file (dir structure of working_dir_step_0) is obtained by running one tool : relocate2.

Bests,
Yinjia

[log.txt](https://github.com/yanhaidong1/TEmarker/files/8755674/log.txt)

**Comment by yanhaidong1** [comment]
Hey Yinjia,

The SRR800842_1_relocate2_nonredundant.bed and SRR800842_1.sorted.bam are what you need. 
The TEmarker_bed.py just copy these two files to output_dir_0. 

I will try this and to see whether I met the issue.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi,

Thanks. By the way, my commad is ~/wangyinjia/TEmarker/TEmarker_bed.py  -d work_dir_step_0 -o output_dir_0 --mcclintock ~/wangyinjia/software/mcclintock/mcclintock.py  -fastq_d fastq_dir -fas_f test_genome.fasta -lib_f TE.lib -tool relocate2 -pros_n 20

Bests,
Yinjia

**Comment by Morriyaty** [comment]
Hi,

When I select more than two tools, I got at least two bed and bam files.  Which software generated files are copied to the output_dir_0?

Bests,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

You are right. I also updated the script that allows to return files to output_dir even you have single sample as input.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi,

Thanks a lot. I will do it later.

Bests,
Yinjia

**Comment by Morriyaty** [comment]
Hi,

I run TEmarker_bed.py for a long time, but it stopped at
`SETUP            checking locations gff: /opt/synData/wangyinjia16/work/F-TE/03.TEmarker/working_dir_step0/output_mcclintock/annotation/Fsr.LG/reference_te_locations/unaugmented_inrefTEs.gff`
I wonder if my gff file is too big?(765M)

Bests,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

There might be several reasons for taking a long time.
1) Many samples in the input fastq directory.
2) Many tools called for the bed generation.
3) a few cores.
4) lots of TEs in gff (in your case)

When you first run the tool, you may not provide the gff, and allow the
tool to help generate that file. TEmarker_bed.py leverages the mcclintock
tool to build the beds, and you can also directly use the mcclintock ('
https://github.com/bergmanlab/mcclintock'). The merit of TEmarker is to
integrate beds derived from various tools and remove some potential
false positives. So you can use any other tool to build the bed files as
the input for the TEmarker_pipeline.py.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi Haidong,

l met some unexpected error when I run TEmarker.

1. TEmarker_genotyping.py, `TEmarker_genotyping.py -d work_dir_step2 -o output_dir_step2 -panTEs_f output_dir_step1_2/opt_pan_TEs.txt -bam_bwa_d bwa_bam -bam_hisat2_d hisat2_bam_out -lib_f All-families.single.clstr.class.fa -pros_n 20` I got the error like this:
`mv: 'bwa_bam/SAMC127036.sort.markdup.bam' and 'bwa_bam/SAMC127036.sort.markdup.bam' are the same file` 
and
`BLAST Database error: No alias or index file found for nucleotide database [work_dir_step2//D02_genos_annotation_dir/temp_lib_db_dir/te_db] in search path [/data/01/user152/workspace/F-TE/07.TEMP/hisat2::]`

Is this matter? But I actually got the output file in output dir.

2.  TEmarker_output.py `TEmarker_output.py -d working_dir_step3 -o output_dir_step3 -genos_f output_dir_step2/opt_te_genotype.txt -m_f sample.txt -fas_f Fsr.LG.fasta`.  I got this:
`Traceback (most recent call last):
  File "/data/01/user152/software/TEmarker/TEmarker_output.py", line 249, in <module>
    main()
  File "/data/01/user152/software/TEmarker/TEmarker_output.py", line 168, in main
    store_final_vcf_line_list,store_final_list_add_ratio_noflt_line = opt_vcf.generate_vcf(genotype_file, chr_num_dic, all_name_list, store_change_sp_nm_dic,read_sup)
  File "/data/01/user152/software/TEmarker/TEmarker_utils/TM_opt_vcf.py", line 154, in generate_vcf
    genotype = annot_col[2]
IndexError: list index out of range`

Could you tell me how can I fix these errors? :)

Bests,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

For the question 1, I updated the 'TEmarker_genotyping.py' and you can download a new one to re-run. Please let me know if it works.
For the question 2, looks like genotype has no annotation due to error caused in question 1. Also, would you mind send an sample of your data that I can have a trying. 

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi Haidong,

Thanks a lot for your reply. I will try question 1 immediately, but it will take some time. Once it was finished, I will let you know.

My data were pretty large (bam ~70G). When question 1 was successfully run, I will share the opt_te_genotype.txt and ref.fasta.
with you.

Bests,
Yinjia

**Comment by Morriyaty** [comment]
Hi Haidong,

Step 1 has been finished, log file and output have been uploaded.

But step 2 showed the same error. 

`TEmarker_output.py -d working_dir_step3 -o output_dir_step3 -genos_f output_dir_step22/opt_te_genotype.txt -m_f sample.txt -fas_f Fsr.LG.fasta`

Bests,
Yinjia
[log.txt](https://github.com/yanhaidong1/TEmarker/files/10926889/log.txt)
[opt_te_genotype.txt](https://github.com/yanhaidong1/TEmarker/files/10926891/opt_te_genotype.txt)
[sample.txt](https://github.com/yanhaidong1/TEmarker/files/10926896/sample.txt)
genome file : https://drive.google.com/drive/folders/18_n6qnKnaZ1ohJVDv5wK8yZ5aPvwGXwk?usp=sharing

**Comment by yanhaidong1** [comment]
Hey Yinjia,

Thanks for the sharing. 

I just fixed the issue of step2 as there are something need to reformatted to fit your data.
Would you download the TEmarker again and do the running?

Also please change 'Ebaileyi12.sort.mardup' to 'Ebaileyi12.sort.markdup' in your sample list file because you need to keep the same name shown in the opt_te_genotype.txt

I just have a tried and can get the final output files. Please let me if it works. Thanks

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hey Haidong,

It occurred an output file error like this:
`Traceback (most recent call last):
  File "/data/01/user152/software/TEmarker/update230309/TEmarker/TEmarker_output.py", line 273, in <module>
    main()
  File "/data/01/user152/software/TEmarker/update230309/TEmarker/TEmarker_output.py", line 171, in main
    with open(working_dir + '/opt.vcf', 'w') as opt:
FileNotFoundError: [Errno 2] No such file or directory: 'working_dir_step33//opt.vcf'`

Such an error (output files not found) not only showed in this script but also another script (TEmarker_genotyping.py, TEmarker_panTEs.py)

Bests,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

Not very understand this point you came up with. I just tried your data and can get the output without any issue using the TEmarker_output.py. For the other two files 'TEmarker_genotyping.py, TEmarker_panTEs.py' looks like you can get right files since you sent me the right file of 'opt_te_genotype.txt'. 

Also, not sure whether you already ran the TEmarker_output.py using the fixed scripts and could successfully get the outputs.

Please correct me if my understanding is wrong. Thanks.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi Haidong,

I am sorry that my unclear expression confused you. When I run command `/data/01/user152/software/TEmarker/update230309/TEmarker/TEmarker_output.py -d working_dir_step33 -o output_dir_step33 -genos_f output_dir_step22/opt_te_genotype.txt -m_f /data/01/user152/workspace/F-TE/07.TEMP/hisat2/sample.txt -fas_f /data/01/user152/workspace/F-TE/07.TEMP/hisat2/ref/Fsr.LG.fasta`, 
I got the error like this:
`After the duplication filtration, 0 TEs are removed
Traceback (most recent call last):
  File "/data/01/user152/software/TEmarker/update230309/TEmarker/TEmarker_output.py", line 273, in <module>
    main()
  File "/data/01/user152/software/TEmarker/update230309/TEmarker/TEmarker_output.py", line 171, in main
    with open(working_dir + '/opt.vcf', 'w') as opt:
FileNotFoundError: [Errno 2] No such file or directory: 'working_dir_step33//opt.vcf'`

It looks like an output file error. For 'TEmarker_genotyping.py, TEmarker_panTEs.py', I run them successfully by 'touch output file before running the command', otherwise, similar 'No such file or directory' errors will occur.

Bests,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

Have you revised the 'Ebaileyi12.sort.mardup' to 'Ebaileyi12.sort.markdup' in the sample.txt? 

I hoped I tried the exact same files as yours. Last night, I can run using your file and obtained the outputs without meeting any issue. Please check this output file.
[opt.zip](https://github.com/yanhaidong1/TEmarker/files/10932630/opt.zip)

Also, I attached my command line:

![Screen Shot 2023-03-09 at 9 35 35 AM](https://user-images.githubusercontent.com/35510112/224057427-aa7cb004-ce13-4966-9e63-cff079334381.png)

Let me know if it will help or not.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi Haidong,

I have corrected the sample.txt and run the same command as you mentioned above. But it didn't work and showed the same error.

Could you share the TEmarker_output.py which you run last night? (not download from the git hub)

Bests,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

[TEmarker.zip](https://github.com/yanhaidong1/TEmarker/files/10932932/TEmarker.zip)

Please check this zip file.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi Haidong,

The script ran without error this time because I ran 'mkdir output_dir working_dir' before running the scripts.

Thanks for your help.

Bests,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

Great! 

Let me know if you have any other questions.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi Haidong,

This is the output file.

![微信截图_20230313193752](https://user-images.githubusercontent.com/68643810/224691341-b8b38094-0d57-4787-8d8b-c80b9e7f451f.png)

The CHROM in the example is "1", but it was named "LG01" in the reference fasta file. Would you mind updating the script to retain the original chromosome name?

Bests,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

I just updated the scripts 'TEmarker_output.py'. Please have a trying.

Also, please check the 'working_dir' that stores the 'opt_original_chrID_and_IDs_in_output_VCF.txt' which will tell you the correspondence between the IDs.

Let me know if needs more modification.

Thanks,
Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi Haidong,

Thanks for your new script.

I check the 'working_dir' and 'output_dir', I didn't find 'opt_original_chrID_and_IDs_in_output_VCF.txt'. Is this an error?

![微信截图_20230314093606](https://user-images.githubusercontent.com/68643810/224869933-6089f896-c233-4332-9a8e-4609f71fa84b.png)

Bests,
Yinjia

**Comment by yanhaidong1** [comment]
Hey Yinjia,

Maybe you could download the TEmarker again from the github and have a trying. You can find the TEmarker_output.py has been updated today and it works for me to get the new file. Let me know if it works. Thanks.

Best wishes,
Haidong

**Comment by Morriyaty** [comment]
Hi Haidong,

Ok, I will try it immediately.

Bests,
Yinjia

update on 10:03: I got this. Thanks
